on:
  push:
    branches:
    - master

permissions:
  id-token: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist
    - uses: actions/deploy-pages@v1
